def main():
    atlhetes = ["Virginia Thrasher", "Nathan Adrian", "Caeleb Dressel", "Anthony Ervin", "Jimmy Feigen", "Ryan Held", "Michael Phelps", "Blake Pieroni", "Katie Ledecky", "Ryan Murphy", "Lilly King", "Simone Biles", "Gabby Douglas", "Laurie Hernandez", "Madison Kocian", "Aly Raisman", "Michael Phelps", "Gunnar Bentz", "Jack Conger", "Conor Dwyer", "Townley Haas", "Ryan Lochte", 
                "Michael Phelps", "Clark Smith", "Katie Ledecky", "Kristin Armstrong", "Maya DiRado", "Missy Franklin", "Katie Ledecky", 
                "Melanie Margalis", "Cierra Runge", "Allison Schmitt", "Leah Smith", "Simone Biles", "Kayla Harrison", "Ryan Murphy", 
                "Michael Phelps", "Simone Manuel", "Michelle Carter", "Anthony Ervin", "Katie Ledecky",
                "Maya DiRado", "Jeff Henderson", "Amanda Elmore", "Tessa Gobbo", "Elle Logan", "Meghan Musnicki", "Amanda Polk", "Emily Regan", "Lauren Schmetterling", 
                "Kerry Simmonds", "Katelin Snyder", "Nathan Adrian", "Kevin Cordes", "Caeleb Dressel", "Cody Miller", "Ryan Murphy", "Michael Phelps", 
                "David Plummer", "Tom Shields", "Kathleen Baker", "Lilly King", "Simone Manuel", "Katie Meili", "Olivia Smoliga", "Dana Vollmer", 
                "Abbey Weitzeil", "Kelsi Worrell", "Simone Biles", "Bethanie Mattek-Sands", "Jack Sock", "Christian Taylor", "Simone Biles", 
                "Brianna Rollins", "Tianna Bartoletta", "Kerron Clement", "Ryan Crouser", "Ashton Eaton", "Dalilah Muhammad", "Helen Maroulis", "Morolake Akinosun", 
                "Tianna Bartoletta", "Tori Bowie", "Allyson Felix", "English Gardner", "Connor s", "Caroline Clark", "Kami Craig", "Rachel Fattal", "Aria Fischer", 
                "Makenzie Fischer", "Kaleigh Gilchrist", "Samantha Hill", "Ashleigh Johnson", "Courtney Mathewson", "Madeline Musselmann", "Kiley Neushul", "Melissa Seidemann", 
                "Maggie Steffens", "Matthew Centrowitz", "Kyle Clemons", "Arman Hall", "Tony McQuay", "LaShawn Merritt", "Gil Roberts",
                "David Verburg", "Taylor Ellis-Watson", "Allyson Felix", "Phyllis Francis", "Natasha Hastings", "Francena McCorory", "Courtney Okolo", "Seimone us", "Sue Bird", 
                "Tamika Catchings", "Tina Charles", "Elena Delle Donne", "Sylvia Fowles", "Brittney Griner", "Angel McCoughtry", "Maya Moore", "Breanna Stewart", "Diana Taurasi", 
                "Lindsay Whalen", "Gwen Jorgensen", "Carmelo Anthony", "Harrison Barnes", "Jimmy Butler", "DeMarcus Cousins", "DeMar DeRozan", "Kevin Durant", "Paul George", "Draymond Green", "Kyrie Irving", 
                "DeAndre Jordan", "Kyle Lowry", "Klay Thompson", "Claressa Shields", "Kyle Snyder", "Brady Ellison", "Zach Garrett", "Jake Kaminski", "Chase Kalisz", "Maya DiRado", "Katie Ledecky", 
                "Simone Manuel", "Lia Neal", "Allison Schmitt", "Dana Vollmer", "Amanda Weir", "Abbey Weitzeil", "Alexander", "David Boudia", "Steele Johnson", "Kathleen Baker", "Travis Stevens", 
                "Sam Dorman", "Michael Hixon", "Daryl Homer", "Josh Prenot", "Aly Raisman", "Michael Phelps", "Tori Bowie", "Kelly Catlin", "Chloé Dygert", "Sarah Hammer", "Jennifer Valente", "Gevvie Stone", 
                "Connor Jaeger", "Simone Manuel", "Justin Gatlin", "Madison Kocian", "Rajeev Ram", "Venus Williams", "Allyson Felix", "Laurie Hernandez", "Will Claye", "Sarah Hammer", "Danell Leyva", "Danell Leyva", "Aly Raisman", "Evan Jager", "Nia Ali", "Brittney Reese", "Lucy Davis", "Kent Farrington", "Beezie Madden", "McLain Ward", "Joe Kovacs", "Sandi Morris", "Alise Willoughby", "Paul Chelimo", "Shakur Stevenson", "Corey Cogdell", "Cody Miller",
                "Leah Smith", "Dana Vollmer", "Conor Dwyer", "David Plummer", "Katie Meili", "Phillip Dutton", "Maya DiRado", "Nathan Adrian", "Brady Ellison", "Nico Hernández", "Allison Brock", "Laura Graves", "Kasey Perry-Glass", "Steffen Peters", "Miles Chamley-Watson", "Race Imboden", "Alexander Massialas", "Gerek Meinhardt", "Kim Rhode", "Nathan Adrian", "Steve Johnson", "Jack Sock", "Monica Aksamit", "Ibtihaj Muhammad", "Dagmara Wozniak", "Mariel Zagunis", "LaShawn Merritt", "Matt Kuchar", "Alexander Naddour", "Sarah Robles", "Clayton Murphy", "Sam Kendricks", "Emma Coburn", "Simone Biles", "Jennifer Simpson", "Caleb Paine", "Tori Bowie", "Kristi Castlin", "April Ross", "Kerri Walsh Jennings", "Ashley Spencer", "David Boudia", "Jackie Galloway", "Rachael Adams", "Foluke Akinradewo", "Kayla Banwarth", "Alisha Glass", "Christa Harmotto", "Kimberly Hill", "Jordan Larson", "Carli Lloyd", "Karsta Lowe", "Kelly Murphy", "Kelsey Robinson", "Courtney Thompson", "J'den Cox", "Galen Rupp", "Matthew Anderson", "Micah Christenson", "Maxwell Holt", "Thomas Jaeschke", "Davie Lee", "William Priddy", "Aaron Russell", "Taylor Sander", "Erik Shoji", "Kawika Shoji", "David Smith", "Murphy Troy",
                "Adam Peaty", "Joe Clarke", "Jack Laugher", "Chris Mears", "Philip Hindes", "Jason Kenny", "Callum Skinner", "Helen Glover", "Heather Stanning", "Alex Gregory", "Constantine Louloudis", "George Nash", "Mohamed Sbihi", "Steven Burke", "Ed Clancy", "Owain Doull", "Bradley Wiggins", "Paul Bennett", "Scott Durant", "Matt Gotrel", "Matt Langridge", "Tom Ransley", "Pete Reed", "William Satch", "Andrew Triggs Hodge", "Phelan Hill", "Katie Archibald", "Elinor Barker", "Joanna Rowsell", "Laura Trott", "Mo Farah", "Max Whitlock", "Justin Rose", "Max Whitlock", "Jason Kenny", "Andy Murray", "Charlotte Dujardin", "Giles Scott", "Laura Trott", "Jason Kenny", "Alist Brownlee", "Saskia Clark", "Hannah Mills", "Jade Jones", "Nick Skelton", "Great Britain", "Maddie Hinch", "Laura Unsworth", "Crista Cullen", "Hannah Macleod", "Georgie Twigg", "Helen Richardson-Walsh", "Susannah Townsend", "Kate Richardson-Walsh", "Sam Quek",
                "Alex Danson", "Giselle Ansley", "Sophie Bray", "Hollie Webb", "Shona McCallin", "Lily Owsley", "Nicola White", "Liam Heath", "Nicola Adams", "Mo Farah", "Jazmin Carlin", "Siobhan-Marie O'Connor", "James Guy", "Stephen Milne", "Duncan Scott", "Daniel Wallace", "Robbie Renwick", "Vicky Thornley", "Katherine Grainger", "David Florence", "Richard Hounslow", "Robertson", "Ruaridh McConnochie", "Phil Burgess", "Dan Norton", "James Rodwell", "Tom Mitchell", "Dan Bibby", "James Davies", "Ollie Lindsay-Hague", "Sam Cross", "Marcus Watson", "Mark Bennett", "Rugby sevens", "Fiona Bigwood", "Charlotte Dujardin", "Carl Hester", "Spencer Wilton", "Bryony Page", "Jazmin Carlin", "Karen Bennett", "Olivia Carnegie-Brown", "Jessica Eddie", "Katie Greves", "Frances Houghton", "Zoe Lee", "Polly Swann", "Melanie Wilson", "Zoe De Toledo", "Becky James", "James Guy", "Adam Peaty", "Duncan Scott", "Chris Walker-Hebborn", "Jessica Ennis-Hill", "Nick Dempsey", "Louis Smith", "Callum Skinner", "Mark Cavendish", "Becky James", "Jack Laugher", "Liam Heath", "Jon Scho", "Jonathan Brownlee", "Lutalo Muhammad", "Joseph Joyce", "Edward Ling", "Tom Daley", "Daniel Goodfellow", "Chris Froome", "Steven Scott", "Sally Conway", "Max Whitlock", "Greg Rutherford", "Sophie Hitchon", "Amy Tinkler", "Nile Wilson", "Katy Marchant", "Joshua Buatsi", "Marcus Ellis", "Chris Langridge", "Daryll Neita", "Asha Philip", "Desiree Henry", "Dina Asher-Smith", "Vicky Holland", "Bianca Walkden", "Emily Diamond", "Eilidh Doyle", "Anyika Onuora", "Kelly Massey", "Christine Ohuruogu",
                "Zhang Mengxue", "Shi Tingmao", "Wu Minxia", "Long Qingquan", "Chen Aisen", "Lin Yue", "Sun Yang", "Deng Wei", "Chen Ruolin", "Liu Huixia", "Shi Zhiyong", "Xiang Yanmei", "Ding Ning", "Ma Long", "Wang Zhen", "Gong Jinjie", "Zhong Tianshi", "Shi Tingmao", "Meng Suping", "Cao Yuan", "Ding Ning", "Li Xiaoxia", "Liu Shiwen", "Ma Long", "Xu Xin", "Zhang Jike", "Zhao Shuai", "Ren Qian", "Fu Haifeng", "Zhang Nan", "Liu Hong", "Chen Long", "Chen Aisen", "Zheng Shuyin", "Yuan Xinyue", "Zhu Ting", "Yang Fangxu", "Gong Xiangyu", "Wei Qiuyue", "Zhang Changni", "Lin Li", "Ding Xia", "Yan Ni", "Liu Xiaotong", "Xu Yunli", "Hui Ruoqi", "Lü Xiaojun", "Du Li", "Sun Yang", "Xu Jiayu", "Li Xiaoxia", "Zhang Binbin", "Hao Jialu", "Sun Yiwen", "Sun Yujie", "Xu Anqi", "Zhang Jike", "Cai Zelin", "Tian Tao", "Dong Dong", "Chen PeinaSai", "He Zi", "Zhang Wenxiu", "Huang Xuechen", "Sun", "Si Yajie", "Gu Xiao", "Guo Li", "Huang Xuechen", "Li Xiaolu", "Liang Xinping", "Sun Wenyan", "Tang Mengni", "Yin Chengxin", "Zeng", "Yin Junhua", "Yi Siling", "Sun Yiwen", "Pang Wei", "Deng Shudi", "Lin Chaopan", "Liu Yang", "You Hao", "Zhang Chenglo",
                "Fu Yuanhui", "Fan Yilin", "Mao Yi", "Shang Chunson", "Tan Jiaxin", "Wang Yan", "Cheng Xunzhao", "Cao Yuan", "Qin Kai", "Du Li", "Shi Jinglin", "Wang Shun", "Huang Wenyi", "Pan Feihong", "Yu Song", "Li Dan", "Duan Jingli", "Li Yuehong", "Gao Lei", "Dong Bin", "Zhang Nan", "Zhao Yunlei", "Sun Yanan", "Ren Cancan", "Zhang Fengliu", "Hu Jianguan", "Li Qian", "Lü Xiuzhi", "Feng Shanshan",
                "Beslan Mudranov", "Yana Egorian", "Khasan Khalmurzaev", "Inna Deriglazova", "Artur Akhmatkhuzin", "Aleksey Cheremisinov", "Timur Safin", "Yekaterina Dyachenko", "Yuliya Gavrilova", "Yana Egorian", "Sofya Velikaya", "Ekaterina Makarova", "Elena Vesnina", "Aliya Mustafina", "Roman Vlasov", "Davit Chakvetadze", "Evgeny Tishchenko", "Natalia Ishchenko", "Svetlana Romashina", "Vlada Chigireva", "Natalia Ishchenko", "Svetlana Kolesnichenko", "Aleksandra Patskevich", "Elena Prokofyeva", "Svetlana Romashina", "Alla Shishkina", "Gelena Topilina", "Maria Shurochkina", "Russia handball", "Anna Sedoykina", "Polina Kuznetsova", "Daria Dmitrieva", "Anna Sen", "Olga Akopyan", "Anna Vyakhireva", "Marina Sudakova", "Vladlena Bobrovnikova", "Victoria Zhilinskayte", "Yekaterina Marennikova", "Irina Bliznova", "Ekaterina Ilina", "Maya Petrova", "Tatyana Yerokhina", "Victoriya Kalinina", "Handball", "Abdulrashid Sadulaev", "Margarita Mamun", "Aleksander Lesun", "Vera Biriukova", "Anastasia Bliznyuk", "Anastasia Maksimova", "Anastasiia Tatareva", "Maria Tolkacheva", "Soslan Ramonov", "Vitalina Batsarashkina", "Tuyana Dashidorzhieva", "Ksenia Perova", "Inna Stepanova", "Archery",
                "Sofya Velikaya", "Denis Ablyazin", "David Belyavskiy", "Nikolai Kuksenkov", "Nikita Nagornyy", "Ivan Stretovich", "Yuliya Yefimova", "Angelina Melnikova", "Aliya Mustafina", "Maria Paseka", "Daria Spiridonova", "Seda Tutkhalyan", "Olga Zabelinskaya", "Yuliya Yefimova", "Daria Shmeleva", "Anastasia Voynova", "Sergey Kamenskiy", "Maria Paseka", "Denis Ablyazin", "Valeria Koblova", "Nataliya Vorobyova", "Alexey Denisenko", "Aniuar Geduev", "Yana Kudryavtseva", "Natalia Kuziutina", "Timur Safin", "Vladimir Maslennikov", "Anton Chupkov", "Olga Kochneva", "Violetta Kolobova", "Tatiana Logunova", "Lyubov Shutova", "Aliya Mustafina", "Evgeny Rylov", "Kirill Grigoryan", "Stefania Elfutina", "Denis Dmitriev", "Denis Ablyazin", "Sergey Semenov", "Roman Anoshkin", "David Belyavskiy", "Anastasia Belyakova", "Vladimir Nikitin", "Ekaterina Bukina", "Anna Ustyukhina", "Maria Borisova", "Ekaterina Prokofyeva", "Elvina Karimova", "Nadezhda Fedotova", "Olga Belova", "Ekaterina Lisunova", "Anastasia Simanovich", "Anna Timofeeva", "Evgenia Soboleva", "Evgeniya Ivanova", "Anna Grineva", "Anna Karnaukh", "Vitaly Dunaytsev" ,
                "Michael Jung", "Philipp Wende", "Lauritz Schoof", "Karl Schulze", "Hans Gruhne", "Annekatrin Thiele", "Carina Bär", "Julia Lier", "Lisa Schmidla", "Barbara Engleder", "Henri Junghänel", "Kristina Bröring-Sprehe", "Sönke Rothenberger", "Dorothee Schneider", "Isabell Werth", "Christoph Harting", "Christian Reitz", "Sebastian Brendel", "Fabian Hambüchen", "Kristina Vogel", "Laura Ludwig", "Kira Walkenhorst", "Max Rendschmidt", "Almuth Schult", "Josephine Henning", "Saskia Bartusiak", "Leonie Maier", "Annike Krahn", "Simone Laudehr", "Melanie Behringer", "Lena Goeßling", "Alexandra Popp", "Dzsenifer Marozsán", "Anja Mittag", "Tabea Kemme", "Sara Däbritz", "Babett Peter", "Mandy Islacker", "Melanie Leupolz", "Isabel Kerschowski", "Laura Benkarth", "Svenja Huth", "Sebastian Brendel", "Jan Vandrey", "Max Rendschmidt", "Tom Liebscher", "Max Hoff", "Marcus Gross", "Thomas Röhler", "Sandra Auffarth", "Michael Jung", "Ingrid Klimke", "Julia Krajewski", "Monika Karsch", "Lisa Unruh", "Felix Drahotta", "Malte Jakschik", "Eric Johannesen", "Andreas Kuffner", "Maximilian Munski", "Hannes Ocik", "Maximilian Reinelt", "Richard Schmidt", "Martin Sauer (cox)",
                "Angelique Kerber", "Isabell Werth", "Franziska Weber", "Tina Dietze", "Han Ying", "Petrissa Solja", "Shan Xiaona", "Sabrina Hering", "Franziska Weber", "Steffi Kriegerstein", "Tina Dietze", "Timo Horn", "Jeremy Toljan", "Lukas Klostermann", "Matthias Ginter", "Niklas Süle", "Sven Bender", "Max Meyer", "Lars Bender", "Davie Selke", "Leon Goretzka", "Julian Brandt", "Jannik Huth", "Philipp Max", "Robert Bauer", "Max Christiansen", "Grischa Prömel", "Serge Gnabry", "Nils Petersen", "Laura Vargas Kolesniche", "Kristina Vogel", "Miriam Welte", "Sophie Scheder", "Kristina Bröring-Sprehe", "Denis Kudla", "Patrick Hausding", "Christian Ahlmann", "Meredith Michaels-Beerba", "Daniel Deusser", "Ludger Beerbaum", "Dimitrij Ovtcharov", "Timo Boll", "Bastian Steger", "Germany", "Linus Butt", "Moritz Fürste", "Florian Fuchs", "Mats Grambusch", "Tom Grambusch", "Martin Häner", "Tobias Hauke", "Timm Herzbruch", "Nicolas Jacobi", "Mathias Müller", "Timur Oruz", "Christopher Rühr", "Moritz Trompertz", "Niklas Wellen", "Christopher Wesley", "Martin Zwicker", "Erik Heil", "Thomas Plößel", "Lisa Hahn", "Franzisca Hauke", "Hannah Krüger", "Nike Lorenz", "Marie Mävers", "Julia Müller", "Janne Müller-Wieland", "Pia-Sophie Oldhafer", "Selin Oruz", "Katharina Otte", "Cécile Pieper", "Kristina"
                ]
    
    sponsors = [
        'Nike', 'Adidas', 'Speedo', 'Under Armor'
    ]

    i=0
    for a in atlhetes:
        for s in sponsors:
            if i%10==0:
                print("\nThe athleteName, nameOfSponsor of sponsor of atheltes are:")
            print(f"{a}, {s}")

            i += 1


if __name__ == "__main__":
    main()